name: Test
on: [pull_request_target]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Cache README
      id: cache_readme
      uses: actions/cache@v2.1.2
      with:
        path: README.md
        key: v1-${{ hashFiles('README.md') }}
        restore-keys: |
          v1-
