name: Test
on:
  pull_request_target:
    branches: [ master ]
    types: [ labeled ] # 'abc' label

jobs:
  label:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'abc')
    permissions:
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Remove label
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "abc",
          });
