name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Wait
      run: echo 12345

    - name: Wait
      run: echo ${{ secrets.SECRET_SECRET }}

    - name: Wait
      run: echo 12345
