name: Test 2
concurrency: abcd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Wait
      run: sleep 120
  abcd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Wait
      run: sleep 120
